// per-line-type blurbs for the hover cards in the line-type menu
const DESCRIPTIONS = {
  line: 'Close-to-close line, each segment colored by its direction.',
  line_solid: 'Close-to-close line in a single color.',
  candles: 'Japanese candlesticks: body from open to close, wicks to high/low, colored by direction.',
  candles_hollow: 'Candles colored against the prior close; hollow when the bar closed above its open, filled when below.',
  candles_hollow_plain: "Single-color candles, hollow or filled by the bar's own open/close.",
  candles_solid_plain: 'Single-color solid candlesticks.',
  bollinger_bars: "John Bollinger's fixed-width candles: green/red body from open to close, wicks drawn as blue blocks to the high and low — the full traded range reads at a glance.",
  area: 'Close line over a soft gradient fill.',
  bars: 'OHLC bars: open tick left, close tick right, colored by direction.',
  bars_solid: 'OHLC bars in a single color.',
  dots: 'A dot at each close, colored by direction.',
  dots_solid: 'A dot at each close in a single color.',
  volume_dots: 'Dots at each close, sized by volume and colored by direction.',
  volume_dots_solid: 'Volume-sized dots in a single color.',
  volume_candles: 'Candlesticks whose body width scales with each bar\'s volume.',
  histogram: 'Columns from the plot floor to each close, colored by direction.',
  histogram_solid: 'Columns from the plot floor to each close in a single color.',
  baseline: 'Close line split at a draggable baseline: green above, red below, with soft washes toward the line.',
  hlc: 'High/low band with thin boundary lines and the close as the main line.',
  hlc_bars: 'Per-bar blocks: green from close to high, red from close to low, dashes at each level.',
  snake: 'Smooth merged high/low bands blending through the closes, with a dot at each close.',
  step_line: 'Close line stepping horizontally, then vertically, colored by direction.',
  step_line_solid: 'Stepped close line in a single color.',
  jointed_line: 'Close-to-close line with a dot at each datapoint.',
  jointed_line_solid: 'Jointed line in a single color.',
  low_high: 'A vertical bar spanning each period\'s low to high, colored by direction.',
  low_high_solid: 'Low-to-high range bars in a single color.',
  heikin_ashi: 'Smoothed candles that average each bar with the prior one — trends read cleaner, noise fades.',
  kagi: 'Reversal-driven line, thick ("yang") after breaking the prior high and thin ("yin") below the prior low. Time spacing is ignored.',
  line_break: 'Three-line break: a new line only when the close breaks the range of the last three lines.',
  renko: 'Fixed-size price bricks — one brick per move, two to reverse. Time spacing is ignored.',
  range_bars: 'A new bar completes each time the high–low range reaches a fixed size.',
  point_figure: 'X and O columns built from box-size moves with a 3-box reversal. Time spacing is ignored.',
};

export default DESCRIPTIONS;
